[#1194] Add aggregation support for TPGM.
ChrizZz110/gradoop pull request #7
Opened 2019-04-10 14:18 UTC by p-f

- Add min- and max-time aggregations.

fixes #1194

2019-05-02 14:28 UTC, ChrizZz110 commented
First comment (haven't looked through all): Good job! You can reduce the amount of classes by removing the abstract from MinTime and MaxTime and let them implement both vertex and edge interfaces. Also rename `AbstractTimeStampAggregateFunction` to `AbstractTimeAggregateFunction`

2019-05-03 11:46 UTC, ChrizZz110 commented
I think you misundestood ... e.g. let `MaxTime` implement `VertexAggregateFunction` and `EdgeAggregateFunction` -> so you do not need `MaxEdgeTime and `MaxVertexTime` classes anymore.
Same for `MinTime`.
Also I think the interfaces `TemporalEdgeAggregateFunction` and `TemporalEdgeAggregateFunction` are not necessary at the moment ... maybe later if we integrate it into temporal grouping.

2019-05-07 11:29 UTC, p-f commented
Ah, I see what you mean, but I think you misunderstood as well:
An `AggregateFunction` will support vertex- and edge-aggregation by default. The `Vertex`- and `EdgeAggregateFunction` interfaces are used to restrict those functions to either vertices or edges, they can not be implemented at the same time.

In this case `MaxTime` will aggregate for both vertices and edges, `MaxVertexTime` will only aggregate vertices and `MaxEdgeTime` will only aggregate edges.

2019-05-08 06:26 UTC, ChrizZz110 commented
Oh that's my fault ... sorry for confusing.

2019-05-08 08:40 UTC, ChrizZz110 commented
I updated the target Branch ... think it will be the best that you merge it into yours.

2019-05-08 13:46 UTC, ChrizZz110 requested changes

2019-05-08 13:46 UTC, ChrizZz110 commented on gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/tpgm/aggregation/MaxTime.java
> +  private static final PropertyValue DEFAULT = PropertyValue.create(Long.MAX_VALUE);
Please use the one from `TemporalElement` class. There you can unify the existing three constants to two default values for min and max

2019-05-08 13:46 UTC, ChrizZz110 commented on gradoop-flink/src/main/java/org/gradoop/flink/model/impl/operators/tpgm/aggregation/MinTime.java
> +  private static final PropertyValue DEFAULT = PropertyValue.create(Long.MIN_VALUE);
Please use the one from `TemporalElement` class. There you can unify the existing three constants to two default values for min and max

2019-05-08 13:46 UTC, ChrizZz110 commented on gradoop-flink/src/test/java/org/gradoop/flink/model/impl/operators/tpgm/aggregation/MinMaxTimeTest.java
> +      new MinVertexTime(keyMinVertex, temporalAttribute, field));
Please add MinTime and MaxTime

2019-05-09 10:06 UTC, p-f commented
Done, had to add a change to the pom, see dbs-leipzig#1256.

2019-05-10 06:41 UTC, ChrizZz110 approved these changes

2019-05-10 06:41 UTC, merged