1195 extend temporalgraph api snapshot
ChrizZz110/gradoop pull request #8
Opened 2019-04-12 13:23 UTC by ChrizZz110

fixes #1195

2019-04-16 10:32 UTC, p-f requested changes
I have some javadoc related comments. Also please link to `Snapshot` or `TemporalGraphOperators#snapshot(TemporalPredicate)` for all of those methods, as the functionality is explained there.

The test is currently checking the functionality of subgraph again, I don't think this is necessary, as there is a snapshot test already. Other opinions on that?

2019-04-16 10:32 UTC, p-f commented on gradoop-flink/src/main/java/org/gradoop/flink/model/api/tpgm/TemporalGraphOperators.java
> +   * {@code t} is a timestamp in ms as long. This will calculate the subgraph of a temporal graph
I think you should write out miliseconds and remove "as long", as the type is clear.

2019-04-16 10:32 UTC, p-f commented on gradoop-flink/src/main/java/org/gradoop/flink/model/api/tpgm/TemporalGraphOperators.java
> +   *
Use a `<br>` or `<p>` if you want a new line.
(Same with the other comments.)

2019-04-16 10:32 UTC, p-f commented on gradoop-flink/src/main/java/org/gradoop/flink/model/api/tpgm/TemporalGraphOperators.java
> +   * where {@code t1} and {@code t2} are timestamps in ms as long. This will calculate the subgraph
This might be confusing, since the paramters of this method are not called `t1` and `t2`.

2019-04-16 10:32 UTC, p-f commented on gradoop-flink/src/main/java/org/gradoop/flink/model/api/tpgm/TemporalGraphOperators.java
> +   * Extracts a snapshot of a temporal graph using a given temporal predicate. This will calculate
Maybe write
> of this temporal graph

instead to make it clear that this graph if transformed (although that should be clear).

2019-04-16 10:32 UTC, p-f commented on gradoop-flink/src/main/java/org/gradoop/flink/model/api/tpgm/TemporalGraphOperators.java
> +   * The resulting graph is a new logical graph.
Clarify that the result is a temporal graph. (Again, should be clear by the return type of this method, but just to be sure.)

2019-04-18 07:07 UTC, ChrizZz110 commented
Good review! I realized your suggested changes.

> The test is currently checking the functionality of subgraph again, I don't think this is necessary, as there is a snapshot test already. Other opinions on that?

The concept of unit test is to check every method and possibility. Since you do not know which change will be done in the future in these convenience API methods, we have to check, that a call of `TemporalGraph#deletedId(a,b)` returns a equal result to `snapshot(new DeletedIn(a, b))` which in turn returns a equal result to `callForGraph(new Snapshot(new DeletedIn(a, b)))`

2019-05-02 14:01 UTC, merged